name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: weathermonitor_test
          MYSQL_USER: weathermonitor
          MYSQL_PASSWORD: weathermonitor
          MYSQL_ROOT_PASSWORD: weathermonitor
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip
        coverage: xdebug

    - name: Copy .env
      run: cp .env.example .env.testing

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate key
      run: php artisan key:generate --env=testing

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate --env=testing

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse

    - name: Run PHPCS
      run: ./vendor/bin/phpcs

    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: weathermonitor_test
        DB_USERNAME: weathermonitor
        DB_PASSWORD: weathermonitor
      run: php artisan test --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 